# Generated by Django 2.2.7 on 2020-02-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageBuyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageMaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='maker_decided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Maker_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='makers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makerprofile',
            name='cost',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.MstCost'),
        ),
        migrations.AddField(
            model_name='makerprofile',
            name='lang',
            field=models.ManyToManyField(blank=True, to='home.MstLang'),
        ),
        migrations.AddField(
            model_name='makerprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='home.MstSkill'),
        ),
        migrations.AddField(
            model_name='makerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='credit_info',
            field=models.ManyToManyField(blank=True, to='home.CreditInfomation'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
