# Generated by Django 2.2.7 on 2020-02-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200216_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.MstCost'),
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='lang',
            field=models.ManyToManyField(blank=True, null=True, to='home.MstLang'),
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='home.MstSkill'),
        ),
    ]
