# Generated by Django 3.0.3 on 2020-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200216_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-MAIL')),
                ('message', models.TextField(verbose_name='Message')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'コンタクト',
            },
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='lang',
            field=models.ManyToManyField(blank=True, to='home.MstLang'),
        ),
        migrations.AlterField(
            model_name='makerprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='home.MstSkill'),
        ),
    ]
