# Generated by Django 2.2.7 on 2020-02-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200222_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtbOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
            ],
            options={
                'verbose_name_plural': 'オーダー属性',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.MtbOrderType'),
            preserve_default=False,
        ),
    ]
