# Generated by Django 2.2.7 on 2020-02-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200222_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_decide',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_decide_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_post_finish_time',
        ),
    ]
