# Generated by Django 2.2.7 on 2020-02-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200222_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.RenameModel(
            old_name='MtbOrderType',
            new_name='MstOrderType',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.MstStatus'),
        ),
    ]
