# Generated by Django 2.2.7 on 2020-02-23 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200223_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.AddField(
            model_name='like',
            name='like_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Order'),
            preserve_default=False,
        ),
    ]
