# Generated by Django 3.0.3 on 2020-02-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20200223_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='lister',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Lister', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
