# Generated by Django 3.0.3 on 2020-02-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ordermessage_lister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermessage',
            name='lister',
        ),
    ]
